<a href="https://colab.research.google.com/github/Sridevi-coder62/Numpy_Calculations-part-2/blob/main/Numpy_Calculations_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.NumPy Data Types + Search

Create a NumPy array containing integers, floats, and strings. Display the data type of the array and use NumPy to find the positions of all elements greater than 50.

In [2]:
import numpy as np

arr=np.array([10,25,55,75.5,40,90,60])

print("Data type of the array: ", arr.dtype)

positions= np.where(arr > 50)

print("Positions of all elements greater than 50 : ", positions[0])

Data type of the array:  float64
Positions of all elements greater than 50 :  [2 3 5 6]


2.NumPy Shape + Reshape

Given a 1D NumPy array containing 12 integers, display its original shape and reshape it into a 3 × 4 matrix. Then display the new shape.

In [3]:
X = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print("Original shape : ", X.shape)

matrix= X.reshape(3,4)
print("Matrix: ", matrix)

print("New shape: ", matrix.shape)

Original shape :  (12,)
Matrix:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New shape:  (3, 4)


3.NumPy Copy vs View + Sort

Given a NumPy array, create both a copy and a view of the array. Modify one element through the view and one element through the copy. Display the original, copy, and view and determine which modifications affected the original array.

In [4]:
x = np.array([10,20,40,56,78])

copy_x=x.copy()
view_arr=x.view()

copy_x[3]=77
view_arr[2]=22

print("Original array: ", x)
print("Copy array: ", copy_x)
print("View array: ", view_arr)

print("After sorting array: ", np.sort(x))
print("After sorting copy array:  ", copy_x)
print("After sorting view array: ", view_arr)

print("Modification through view affected: yes")
print("Modification through copy affected: No")

Original array:  [10 20 22 56 78]
Copy array:  [10 20 40 77 78]
View array:  [10 20 22 56 78]
After sorting array:  [10 20 22 56 78]
After sorting copy array:   [10 20 40 77 78]
After sorting view array:  [10 20 22 56 78]
Modification through view affected: yes
Modification through copy affected: No


4.NumPy Join + Split

Given two NumPy arrays containing monthly sales data for two different quarters, join the arrays into one array and then split the combined array into four equal parts representing individual months/periods.


In [6]:
quarter1= np.array([1200,1250,2000,7800])
quarter2=np.array([1600,1700,1800,1900])

combined=np.concatenate((quarter1,quarter2))

print("Combined: ", combined)

parts=np.array_split(combined,4)

for i, part in enumerate(parts,1):
  print(f"Part {i}:", part)

Combined:  [1200 1250 2000 7800 1600 1700 1800 1900]
Part 1: [1200 1250]
Part 2: [2000 7800]
Part 3: [1600 1700]
Part 4: [1800 1900]


5.NumPy Iterating + Filter + Search

Given a 2D NumPy array representing employee salaries, iterate through the array and identify employees whose salary is above 50,000. Return the values and their row/column positions using NumPy search/filter operations.

In [7]:
salaries=np.array([[20000,35000],[45000,50000],[67000,90000]])

positions=np.argwhere(salaries > 50000)

values= salaries[salaries > 50000]

print("Salaries above 50,000 : ", values)
print("\nRow and column positions : ")

for i in positions:
  print("Row", i[0], "Column: ", i[1])


Salaries above 50,000 :  [67000 90000]

Row and column positions : 
Row 2 Column:  0
Row 2 Column:  1


6.NumPy Reshape + Sort + Filter + Search

Given a 3D NumPy array representing sales data for multiple stores, reshape it into a suitable 2D structure, sort the sales values, filter values above a given threshold, and identify the original positions of the filtered values.

In [9]:
sales = np.array([
    [[120, 80, 150],
     [200, 90, 170]],

    [[100, 250, 130],
     [180, 110, 300]]
])

sales_2d= sales.reshape(2,6)

print("Sales : ", sales_2d)

sorted_sales=np.sort(sales_2d)

print("Sales after sorting: ", sorted_sales)

threshold=150

filtered_value=sales[sales > threshold]

print("Value above ", threshold , ":")
print(filtered_value)

position = np.argwhere(sales > threshold)

print("Original positions: ")
for i in position:
  print("Store: ",i[0],"Week :", i[1], "Day: ",i[2], "Value: ", sales[tuple(i)])


Sales :  [[120  80 150 200  90 170]
 [100 250 130 180 110 300]]
Sales after sorting:  [[ 80  90 120 150 170 200]
 [100 110 130 180 250 300]]
Value above  150 :
[200 170 250 180 300]
Original positions: 
Store:  0 Week : 1 Day:  0 Value:  200
Store:  0 Week : 1 Day:  2 Value:  170
Store:  1 Week : 0 Day:  1 Value:  250
Store:  1 Week : 1 Day:  0 Value:  180
Store:  1 Week : 1 Day:  2 Value:  300


Python Lists

7.Python List — Data Types + Search

Given a Python list containing integers and strings, identify the data type of each element and find the indexes of all integers greater than 50.

In [10]:
# Python List — Data Types + Search

# Create a list containing integers and strings
data = [25, "Python", 75, "NumPy", 40, 90, "SQL", 60]

# Identify the data type of each element
print("Data types of each element:")

for item in data:
    print(item, "->", type(item).__name__)

# Find indexes of integers greater than 50
indexes = []

for i in range(len(data)):
    if isinstance(data[i], int) and data[i] > 50:
        indexes.append(i)

print("\nIndexes of integers greater than 50:", indexes)

Data types of each element:
25 -> int
Python -> str
75 -> int
NumPy -> str
40 -> int
90 -> int
SQL -> str
60 -> int

Indexes of integers greater than 50: [2, 5, 7]


8.Python List — Shape/Reshape Concept

Given a Python list containing 12 integers, divide it into 3 sublists containing 4 elements each, similar to reshaping a NumPy array into a 3 × 4 structure.

In [11]:
# Python List — Shape/Reshape Concept

# Create a Python list containing 12 integers
numbers = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]

# Divide the list into 3 sublists of 4 elements each
reshaped = [
    numbers[0:4],
    numbers[4:8],
    numbers[8:12]
]

print("Original list:", numbers)
print("\n3 × 4 structure:")
print(reshaped)

Original list: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]

3 × 4 structure:
[[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]]


9.Python List — Copy vs Reference + Sort

Given a Python list, create another list using both direct assignment and slicing. Modify the new lists and determine whether the changes affect the original list. Then sort the lists and compare the results.

In [12]:
# Python List — Copy vs Reference + Sort

# Create the original list
numbers = [50, 20, 80, 10, 40]

# Direct assignment (reference)
reference_list = numbers

# Slicing (creates a copy)
sliced_list = numbers[:]

# Modify the new lists
reference_list[0] = 100
sliced_list[1] = 200

# Display the lists
print("Original list:", numbers)
print("Reference list:", reference_list)
print("Sliced list:", sliced_list)

# Sort the lists
reference_list.sort()
sliced_list.sort()

print("\nAfter sorting:")
print("Original list:", numbers)
print("Reference list:", reference_list)
print("Sliced list:", sliced_list)

Original list: [100, 20, 80, 10, 40]
Reference list: [100, 20, 80, 10, 40]
Sliced list: [50, 200, 80, 10, 40]

After sorting:
Original list: [10, 20, 40, 80, 100]
Reference list: [10, 20, 40, 80, 100]
Sliced list: [10, 40, 50, 80, 200]


10.Python List — Join + Split

Given two Python lists containing sales data from two different months, combine them into a single list and then divide the combined list into four equal sublists.

In [13]:
# Python List — Join + Split

# Sales data from two different months
month1 = [1000, 1200, 1500, 1300]
month2 = [1600, 1800, 1700, 2000]

# Combine the two lists
combined = month1 + month2

print("Combined sales:", combined)

# Divide the combined list into four equal sublists
size = len(combined) // 4

parts = [
    combined[0:size],
    combined[size:2*size],
    combined[2*size:3*size],
    combined[3*size:4*size]
]

print("\nFour equal sublists:")
print("Part 1:", parts[0])
print("Part 2:", parts[1])
print("Part 3:", parts[2])
print("Part 4:", parts[3])

Combined sales: [1000, 1200, 1500, 1300, 1600, 1800, 1700, 2000]

Four equal sublists:
Part 1: [1000, 1200]
Part 2: [1500, 1300]
Part 3: [1600, 1800]
Part 4: [1700, 2000]


11.Python List — Iterating + Filtering + Index Search

Given a nested Python list representing employee salaries across different departments, iterate through the list and find all salaries above 50,000. Return each salary along with its department index and employee index.

In [14]:
# Python List — Iterating + Filtering + Index Search

# Employee salaries for different departments
salaries = [
    [45000, 60000, 55000],   # Department 0
    [48000, 75000, 52000],   # Department 1
    [90000, 40000, 65000]    # Department 2
]

# Iterate through departments and employees
for department_index in range(len(salaries)):
    for employee_index in range(len(salaries[department_index])):

        salary = salaries[department_index][employee_index]

        # Find salaries above 50,000
        if salary > 50000:
            print(
                "Salary:", salary,
                "| Department Index:", department_index,
                "| Employee Index:", employee_index
            )


Salary: 60000 | Department Index: 0 | Employee Index: 1
Salary: 55000 | Department Index: 0 | Employee Index: 2
Salary: 75000 | Department Index: 1 | Employee Index: 1
Salary: 52000 | Department Index: 1 | Employee Index: 2
Salary: 90000 | Department Index: 2 | Employee Index: 0
Salary: 65000 | Department Index: 2 | Employee Index: 2



12.Python List — Nested List Manipulation + Sort + Filter + Search

Given a nested Python list representing sales for multiple stores and products, flatten the required data, sort the sales values, filter values above a specified threshold, and return the store index, product index, and sales value for each matching record.

In [15]:
# Python List — Nested List Manipulation + Sort + Filter + Search

# Sales data for multiple stores and products
sales = [
    [12000, 45000, 60000],   # Store 0
    [30000, 75000, 50000],   # Store 1
    [90000, 40000, 65000]    # Store 2
]

# Flatten the nested list
flat_sales = []

for store in sales:
    for value in store:
        flat_sales.append(value)

# Sort the sales values
sorted_sales = sorted(flat_sales)

print("Sorted sales:", sorted_sales)

# Set the threshold
threshold = 50000

# Filter and find original positions
print("\nSales above", threshold, ":")

for store_index in range(len(sales)):
    for product_index in range(len(sales[store_index])):

        value = sales[store_index][product_index]

        if value > threshold:
            print(
                "Store Index:", store_index,
                "| Product Index:", product_index,
                "| Sales:", value
            )

Sorted sales: [12000, 30000, 40000, 45000, 50000, 60000, 65000, 75000, 90000]

Sales above 50000 :
Store Index: 0 | Product Index: 2 | Sales: 60000
Store Index: 1 | Product Index: 1 | Sales: 75000
Store Index: 2 | Product Index: 0 | Sales: 90000
Store Index: 2 | Product Index: 2 | Sales: 65000
